# Generated by Django 3.0.8 on 2022-01-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='before_price',
            field=models.FloatField(default=0),
        ),
    ]
