# Generated by Django 3.0.8 on 2022-01-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220102_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requeriment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimun', models.CharField(max_length=200)),
                ('recommended', models.CharField(max_length=200)),
                ('so', models.CharField(max_length=50)),
                ('proccesor', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('graphics', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='requeriment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Requeriment'),
        ),
    ]
