# Generated by Django 3.0.8 on 2022-01-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220102_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requeriment',
            options={'verbose_name': 'Requerimientos'},
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=200)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Product')),
            ],
            options={
                'verbose_name': 'Stock',
            },
        ),
    ]
