# Generated by Django 3.0.8 on 2022-01-02 21:55

from django.db import migrations, models
import web.utils


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220102_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web.utils.define_product_path)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
